name: Flask-Application CI-CD Pipeline

on:
  push:  
    branches:
      - main               

permissions:
  contents: write  
env:
  GCR_REPO_NAME: ${{ secrets.GCR_REPO_NAME }}  
  DOCKER_TAR: "docker_image_${{ github.run_number }}.tar"    
  GCP_PROJECT_ID: ${{ secrets.GCP_DEV_PROJECT_ID }}
  GCP_DEV_SA_KEY: ${{ secrets.GCP_DEV_SA_KEY }}
  PAT_GITHUB: ${{secrets.PAT_GITHUB}}

jobs:
  checkout:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3  

  dependency-audit:
    runs-on: ubuntu-latest
    needs: checkout  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  

      - name: Install Python
        uses: actions/setup-python@v3  
        with:
          python-version: '3.8'  

      - name: Install pylint
        run: pip install pylint  

      - name: Run pylint
        run: |
          pylint ./apps/app.py  # Replace with the directory or files you want to audit 